# Generated by Django 3.2.4 on 2021-06-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_order_user'),
        ('accounts', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='orders',
            field=models.ManyToManyField(blank=True, null=True, related_name='customer', to='shop.Order', verbose_name='Заказы'),
        ),
    ]
