# Generated by Django 3.2.4 on 2021-06-24 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_cart_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id', 'category'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
