# Generated by Django 3.2.4 on 2021-07-08 16:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210708_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='features_product',
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='features_for_product', to='shop.ProductFeature', verbose_name='Характеристики'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(db_index=True, default=datetime.datetime(2021, 7, 8, 16, 40, 22, 288873), verbose_name='Дата для получения заказа'),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_features', to='shop.product', verbose_name='Товар'),
        ),
    ]
