# Generated by Django 3.2.4 on 2021-07-08 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210708_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(db_index=True, default=datetime.datetime(2021, 7, 8, 16, 42, 47, 335607), verbose_name='Дата для получения заказа'),
        ),
    ]
