# Generated by Django 3.2.4 on 2021-06-26 16:25

from django.db import migrations, models
import django.db.models.deletion
import shop.utils


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_value_productfeature_feature_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=shop.utils.get_timestamp_path, verbose_name='Главное изображение'),
        ),
        migrations.CreateModel(
            name='AdditionalImageProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=shop.utils.get_timestamp_path, verbose_name='Дополнительное изображение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Дополнительное изображение',
                'verbose_name_plural': 'Дополнительные изображения',
            },
        ),
    ]
