# Generated by Django 3.2.4 on 2021-07-08 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(db_index=True, default=datetime.datetime(2021, 7, 8, 17, 11, 17, 28900), verbose_name='Дата для получения заказа'),
        ),
    ]
