# Generated by Django 3.2.4 on 2021-06-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210626_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='final_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Общая цена'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='related_cart', to='shop.CartProduct', verbose_name='Товары'),
        ),
    ]
