# Generated by Django 3.2.4 on 2021-07-01 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210630_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_terminated',
            field=models.BooleanField(default=False, verbose_name='Поставка товара прекращена'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(db_index=True, default=datetime.datetime(2021, 7, 1, 9, 56, 6, 425369), verbose_name='Дата для получения заказа'),
        ),
    ]
