# Generated by Django 3.2.4 on 2021-07-01 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20210701_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(db_index=True, default=datetime.datetime(2021, 7, 1, 10, 35, 18, 91624), verbose_name='Дата для получения заказа'),
        ),
    ]
